package src.document.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import src.common.exception.ApiErrorCodes;
import src.common.exception.BadRequestException;
import src.document.dto.DocumentDetailsResponse;
import src.document.dto.EmailDocumentInsightsRequest;
import src.document.util.DocumentStatus;
import src.entity.User;
import src.mail.service.MailService;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class DocumentInsightsEmailService {

    private final DocumentService
            documentService;

    private final MailService
            mailService;

    public void sendInsights(
            UUID documentId,
            EmailDocumentInsightsRequest request,
            User currentUser
    ) {
        /*
         * This verifies that the authenticated user
         * has access to the document.
         */
        DocumentDetailsResponse document =
                documentService
                        .getDocumentDetails(
                                documentId,
                                currentUser
                        );

        if (
                document.status() !=
                        DocumentStatus.READY
        ) {
            throw new BadRequestException(
                    ApiErrorCodes.DOCUMENT_NOT_READY,
                    "AI insights can only be emailed for READY documents"
            );
        }

        String recipient =
                currentUser.getEmail();

        String subject =
                buildSubject(
                        document,
                        request.language()
                );

        String body =
                buildBody(
                        document,
                        request,
                        currentUser
                );

        mailService.sendTextEmail(
                recipient,
                subject,
                body
        );
    }

    private String buildSubject(
            DocumentDetailsResponse document,
            String language
    ) {
        if (isBulgarian(language)) {
            return "OurVault AI анализ - " +
                    document.title();
        }

        return "OurVault AI Insights - " +
                document.title();
    }

    private String buildBody(
            DocumentDetailsResponse document,
            EmailDocumentInsightsRequest request,
            User currentUser
    ) {
        boolean bulgarian =
                isBulgarian(
                        request.language()
                );

        StringBuilder body =
                new StringBuilder();

        if (bulgarian) {
            body.append("Здравейте, ")
                    .append(
                            currentUser.getUsername()
                    )
                    .append("!\n\n");

            body.append(
                    "Ето AI анализа, генериран от OurVault.\n\n"
            );

            body.append("Документ: ")
                    .append(
                            document.title()
                    )
                    .append('\n');

            body.append("Работно пространство: ")
                    .append(
                            document.workspaceName()
                    )
                    .append("\n\n");

            body.append("ОБОБЩЕНИЕ\n");
            body.append("--------------------\n");
            body.append(
                    request.summary().trim()
            );
            body.append("\n\n");

            body.append("КЛЮЧОВИ ТОЧКИ\n");
            body.append("--------------------\n");

            appendNumberedList(
                    body,
                    request.keyPoints()
            );

            body.append('\n');

            body.append("ВАЖНИ ФАКТИ\n");
            body.append("--------------------\n");

            appendNumberedList(
                    body,
                    request.importantFacts()
            );

            body.append(
                    "\n\nГенерирано от OurVault"
            );

            return body.toString();
        }

        body.append("Hello ")
                .append(
                        currentUser.getUsername()
                )
                .append(",\n\n");

        body.append(
                "Here are the AI insights generated by OurVault.\n\n"
        );

        body.append("Document: ")
                .append(
                        document.title()
                )
                .append('\n');

        body.append("Workspace: ")
                .append(
                        document.workspaceName()
                )
                .append("\n\n");

        body.append("SUMMARY\n");
        body.append("--------------------\n");
        body.append(
                request.summary().trim()
        );
        body.append("\n\n");

        body.append("KEY POINTS\n");
        body.append("--------------------\n");

        appendNumberedList(
                body,
                request.keyPoints()
        );

        body.append('\n');

        body.append("IMPORTANT FACTS\n");
        body.append("--------------------\n");

        appendNumberedList(
                body,
                request.importantFacts()
        );

        body.append(
                "\n\nGenerated by OurVault"
        );

        return body.toString();
    }

    private void appendNumberedList(
            StringBuilder body,
            List<String> values
    ) {
        if (
                values == null ||
                        values.isEmpty()
        ) {
            body.append("-\n");
            return;
        }

        for (
                int index = 0;
                index < values.size();
                index++
        ) {
            body.append(
                    index + 1
            );

            body.append(". ");

            body.append(
                    values
                            .get(index)
                            .trim()
            );

            body.append('\n');
        }
    }

    private boolean isBulgarian(
            String language
    ) {
        if (language == null) {
            return false;
        }

        return language
                .trim()
                .toLowerCase()
                .startsWith("bg");
    }
}