package src.document.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import src.common.exception.ApiErrorCodes;
import src.common.exception.BadRequestException;
import src.document.dto.DocumentDetailsResponse;
import src.document.dto.EmailDocumentInsightsRequest;
import src.document.util.DocumentStatus;
import src.entity.User;
import src.mail.service.MailService;

import java.util.UUID;

@Service
@RequiredArgsConstructor
public class DocumentInsightsEmailService {

    private final DocumentService
            documentService;

    private final DocumentInsightsPdfService
            documentInsightsPdfService;

    private final MailService
            mailService;

    public void sendInsights(
            UUID documentId,
            EmailDocumentInsightsRequest request,
            User currentUser
    ) {
        /*
         * Verifies that the authenticated user has
         * access to the requested document.
         */
        DocumentDetailsResponse document =
                documentService
                        .getDocumentDetails(
                                documentId,
                                currentUser
                        );

        if (document.status() !=
                DocumentStatus.READY) {

            throw new BadRequestException(
                    ApiErrorCodes.DOCUMENT_NOT_READY,
                    "AI insights can only be emailed for READY documents"
            );
        }

        String recipient =
                currentUser.getEmail();

        String subject =
                buildSubject(
                        document,
                        request.language()
                );

        String body =
                buildBody(
                        document,
                        request,
                        currentUser
                );

        /*
         * Generate the PDF from the insights that were
         * already generated and sent by the frontend.
         *
         * No additional LLM request is performed here.
         */
        byte[] pdf =
                documentInsightsPdfService.generate(
                        document,
                        request,
                        currentUser
                );

        String attachmentFilename =
                buildAttachmentFilename(
                        document.title()
                );

        mailService.sendEmailWithPdfAttachment(
                recipient,
                subject,
                body,
                attachmentFilename,
                pdf
        );
    }

    /*
     * ---------------------------------------------------------
     * SUBJECT
     * ---------------------------------------------------------
     */
    private String buildSubject(
            DocumentDetailsResponse document,
            String language
    ) {
        if (isBulgarian(
                language
        )) {
            return "OurVault AI анализ - " +
                    document.title();
        }

        return "OurVault AI Insights - " +
                document.title();
    }

    /*
     * ---------------------------------------------------------
     * EMAIL BODY
     * ---------------------------------------------------------
     *
     * The detailed insights are intentionally kept in the
     * attached PDF instead of being duplicated in the email.
     */
    private String buildBody(
            DocumentDetailsResponse document,
            EmailDocumentInsightsRequest request,
            User currentUser
    ) {
        if (isBulgarian(
                request.language()
        )) {
            return """
                    Здравейте, %s!

                    AI анализът за документа „%s“ е готов.

                    Работно пространство: %s

                    Към този имейл е приложен PDF отчет, съдържащ:
                    • обобщение на документа;
                    • ключови точки;
                    • важни факти.

                    PDF отчетът е генериран от вече създадения AI анализ в OurVault.

                    Генерирано от OurVault
                    """.formatted(
                    safeUsername(
                            currentUser
                    ),
                    document.title(),
                    document.workspaceName()
            );
        }

        return """
                Hello %s!

                The AI insights for "%s" are ready.

                Workspace: %s

                A PDF report is attached containing:
                • document summary;
                • key points;
                • important facts.

                The PDF report was generated from the AI insights already created in OurVault.

                Generated by OurVault
                """.formatted(
                safeUsername(
                        currentUser
                ),
                document.title(),
                document.workspaceName()
        );
    }

    /*
     * ---------------------------------------------------------
     * ATTACHMENT FILENAME
     * ---------------------------------------------------------
     */
    private String buildAttachmentFilename(
            String documentTitle
    ) {
        String safeTitle =
                documentTitle == null
                        ? ""
                        : documentTitle
                        .trim()
                        .replaceAll(
                                "[^\\p{L}\\p{N}._-]+",
                                "_"
                        )
                        .replaceAll(
                                "_+",
                                "_"
                        )
                        .replaceAll(
                                "^_+|_+$",
                                ""
                        );

        if (safeTitle.isBlank()) {
            safeTitle =
                    "Document";
        }

        return "OurVault_" +
                safeTitle +
                "_Insights.pdf";
    }

    /*
     * ---------------------------------------------------------
     * HELPERS
     * ---------------------------------------------------------
     */
    private String safeUsername(
            User currentUser
    ) {
        if (currentUser.getUsername() == null ||
                currentUser.getUsername()
                        .isBlank()) {

            return currentUser.getEmail();
        }

        return currentUser.getUsername()
                .trim();
    }

    private boolean isBulgarian(
            String language
    ) {
        if (language == null) {
            return false;
        }

        return language
                .trim()
                .toLowerCase()
                .startsWith("bg");
    }
}