spring.datasource.url=jdbc:postgresql://localhost:5432/my_app_db
spring.datasource.username=postgres
spring.datasource.password=postgre123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=your-super-secret-key-your-super-secret-key-123456
jwt.expiration=86400000

app.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.jpa.hibernate.ddl-auto=validate

# Local Ollama server
spring.ai.ollama.base-url=http://localhost:11434

# Embedding model for vector search
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=embeddinggemma

# Chat model for answering questions
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=gemma3:4b

# Models are already downloaded manually
spring.ai.ollama.init.pull-model-strategy=never

rag.search.minimum-similarity=0.35